### ISSUE TITLE
Insert emoji immediately on user hitting enter (and funny emoji suggestions, don't miss them 🎊!)

### ISSUE THREAD

**Issue by mredigonda** [maoschanz/emoji-selector-for-gnome#129] opened 2020-09-07 06:01 UTC
I get that when I press enter on the emoji I want this one gets copied to my clipboard, would it be possible to go one step further and make the emoji be inserted in the current selected textbox (thus avoiding one `CTRL+V`)?

Completely off-topic and just for the fun, I'll leave some emoji suggestions that I got that were pretty interesting.

Here I wanted to write some "happy" emoji.
![Screenshot from 2020-09-06 19-55-39](https://user-images.githubusercontent.com/25920622/92353550-f7c7c500-f0b6-11ea-9ea4-921834b5aeab.png)

And this one speaks for itself
![Screenshot from 2020-09-07 03-00-46](https://user-images.githubusercontent.com/25920622/92353574-07470e00-f0b7-11ea-9d5e-ffce5c3bd125.png)

**Comment by maoschanz** [comment] 2020-09-07 06:36
*duplicate of #15 #49 #42 and probably more*

emulating key inputs in 3rd-party windows is beyond the scope of what an extension should be able to do. Sorry but this is not an onscreen keyboard, it looks insanely hard to do, especially on Wayland, and the only benefit is to avoid one ctrl+v: i'll not do that, i have better things to develop.

-----

concerning the funny tag, while there are easter eggs, these examples are not some of them:

- "happ" is contained in "un**happ**y face", which is the name of this emoji (it's weird there are so few emojis tagged with "happy" itself tho)
- "bad code" is the keyword related to the poop emoji in the gitmoji tagging system https://gitmoji.carloscuesta.me/

**Closed** 2020-09-07 18:28 UTC
Labels: duplicate, enhancement
