### ISSUE TITLE
Click emoji = write emoji in active text box 

### ISSUE THREAD

**Issue by sscarduzio** [maoschanz/emoji-selector-for-gnome#115] opened 2020-05-17 10:57 UTC
I don't know if it is possible in gnome, but the actual usage of this extension should be like this:

1. I'm writing - say -  this text in github, or a document in libreoffice..
2. I need an emoji, so I type Super+e  and click on an emoji🚀
3. I expect the rocket to appear in the text box, not in my clipboard.

Do you think it's possible?

**Comment by maoschanz** [comment] 2020-05-17 12:17
i think it's a duplicate of #49

**Closed by maoschanz** 2020-05-17 12:17 UTC
