### ISSUE TITLE
make Shortcut <Super>.  OR <Super><Period> possible - like the windows default

### ISSUE THREAD

**Issue by twirley** [maoschanz/emoji-selector-for-gnome#130] opened 2020-09-15 10:10 UTC
Hi,

thank you so much for this amazing extension 😃
It is an real deal maker for me to stay on linux more happy ^^

**I don't seem to be able to set Super + Period as an shortcut though.
Like it is the standard-shortcut in Windows.**

I tried to press the shortcut directly.
I tried to write <Super> .
and <Super> <Period> as well <Super><.>
all with no success

I have to switch often between different operating systems, having this as a possibility would really amazing for me.

Thank you so much ☺️

**Comment by maoschanz** [comment] 2020-09-15 10:38
Duplicate of #128 #50 and #53

**Closed by maoschanz** 2020-09-15 10:38 UTC
