### ISSUE TITLE
Arrowing down from search field can land user on blank result emoji

### ISSUE THREAD

**Issue by xurizaemon** [maoschanz/emoji-selector-for-gnome#132] opened 2020-09-27 04:19 UTC
When searching for emoji, using `DOWN_ARROW` from the search field selects the centremost result by default, even if there are no results in that location.

## Steps to reproduce:

* Open Emoji Selector
* type `sparkles`
* Press `DOWN_ARROW`
* From here, it takes 5 x `LEFT_ARROW` to reach the sole result emoji

![image](https://user-images.githubusercontent.com/105608/94355902-d883ec80-00e4-11eb-9f13-0e8f9c6a0ce2.png)

## Workaround

After entering search text, use `TAB` rather than `DOWN_ARROW`. This takes the user to the leftmost search result.

## Proposed solution

If possible, blank result buttons should not be selectable, which would mean that if there are less than 5 results, `DOWN_ARROW` either takes the user to the leftmost or rightmost emoji (depending on whether the difference in behaviour between `TAB` and `DOWN_ARROW` is desired).

**Comment by maoschanz** [comment] 2020-09-27 15:10
>After entering search text, use <kbd>TAB</kbd> rather than <kbd>DOWN_ARROW</kbd>

... and that's all. It's how you're supposed to navigate using the keyboard in any existing UI i've ever heard of, and the extension is designed to do this, not to use arrows.

This is closed as a duplicate of #52 and #116. The solution was also explained in #33 and in #131 which is the issue opened just before yours.

**Closed** 2020-09-27 15:11 UTC
Labels: duplicate

**Comment by xurizaemon** [comment] 2020-09-27 18:50
Ah, apologies for the duplicate. I did check the issue queue but must have not spotted the four existing closed issues.

From your comment on #52 I think you are saying that you'd be open to resolving this if an improved behaviour was contributed, and perhaps that it's an issue more to do with default Gnome behaviour than code in this module?

> If you're motivated to override the way the focus management works in GNOME Shell menus, you can contribute

The current behaviour seems to be confusing quite a few users, given the number of duplicate issues seen here! Sorry to add to the noise.

**Comment by maoschanz** [comment] 2020-10-04 01:34
>it's an issue more to do with default Gnome behaviour than code in this module?

Yes, but the behavior is normal, down-arrow means "go down" (from this centered entry, so it selects the centered one), tab means "go the next button". This is a sane standard.

>given the number of duplicate issues seen here

33 and 131 are only partially about that. For example 131 is mainly about how the left arrow is designed, in menus, to go to the parent level in the hierarchy of submenus, thus closing the category of emojis (if you're browsing one). As you can see there is nothing in this extension that i designed to be used with arrows, each arrow has a behavior defined by GNOME Shell.

----

Something that can realistically be fixed, and that is actually already fixed but not released, is to disable the buttons of the search results when they're empty. So people will complain about getting the least pertinent result selected instead of the first one, and i'll continue to tell them about tab
