### ISSUE TITLE
Keyboard selection of emoji should start at left, not centre

### ISSUE THREAD

**Issue by EpicPilgrim** [maoschanz/emoji-selector-for-gnome#116] opened 2020-05-25 00:02 UTC
I live in keyboard shortcuts, so I launch the emoji selector with Meta-E (thanks for making that a possibility!) However, whether I want the most recent emoji (left-most), or I want to search then select the exact match, as soon as I hit the "down arrow", it highlights the centre of the emoji selection line and I have to left-arrow over to most recent or most appropriate search result. The selector should default to the left-most emoji when I down-arrow.

Otherwise, this is a brilliant addon that helps fill the gap for non-GTK3 apps!

**Comment by maoschanz** [comment] 2020-05-25 00:52
duplicate of #52 (summary of the discussion: it's designed to be navigated with tab)

**Closed by maoschanz** 2020-05-25 00:52 UTC
Labels: duplicate
