### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by yob** [maoschanz/emoji-selector-for-gnome#135] opened 2020-10-05 01:16 UTC
As of this morning the emoji picker fails to initialize when I login:

Here's the error in my syslog:
```
Oct  5 10:35:59 tak gnome-shell[2324]: JS ERROR: Extension emoji-selector@maestroschan.fr: TypeError: meta is null#012_patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13#012_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18#012_renderPanelMenuHeaderBox@/home/jh/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/extension.js:326:31#012EmojisMenu@/home/jh/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/extension.js:232:8#012enable@/home/jh/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/extension.js:450:18#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:269:22#012start@resource:///org/gnome/shell/ui/main.js:159:5#012@<main>:1:47
Oct  5 10:35:59 tak gnome-shell[2324]: JS ERROR: Extension window-list@gnome-shell-extensions.gcampax.github.com: TypeError: this.setWorkspacesFullGeometry is not a function#012_onWorkAreasChanged@/home/jh/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/windowPicker.js:60:14#012_init@/home/jh/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/windowPicker.js:37:14#012_init@/home/jh/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/windowPicker.js:127:35#012enable@/home/jh/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com/extension.js:1133:29#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:269:22#012start@resource:///org/gnome/shell/ui/main.js:159:5#012@<main>:1:47
```

I'm running a debian testing system, which had various parts of gnome 3.38 appear recently (versions are from and to):

```
2020-10-03 08:55:49 upgrade gdm3:amd64 3.36.3-1 3.38.0-2
2020-10-03 08:55:50 upgrade gnome-session-bin:amd64 3.36.0-2+b1 3.38.0-2
2020-10-03 08:55:50 upgrade gnome-session:all 3.36.0-2 3.38.0-2
2020-10-03 08:55:50 upgrade gnome-shell-extensions:all 3.36.2-1 3.38.0-2
2020-10-03 08:55:50 upgrade gnome-shell-extension-prefs:amd64 3.36.6-1 3.38.0-2
2020-10-03 08:55:50 upgrade gnome-shell-common:all 3.36.6-1 3.38.0-2
2020-10-03 08:55:50 upgrade gjs:amd64 1.64.3-1 1.66.0-1
2020-10-03 08:55:51 upgrade gnome-shell:amd64 3.36.6-1 3.38.0-2
2020-10-03 08:55:51 upgrade gnome-settings-daemon-common:all 3.36.1-1 3.38.0-2
2020-10-03 08:55:51 upgrade gnome-settings-daemon:amd64 3.36.1-1 3.38.0-2
2020-10-03 08:55:51 upgrade libgdm1:amd64 3.36.3-1 3.38.0-2
2020-10-03 08:55:51 upgrade gnome-session-common:all 3.36.0-2 3.38.0-2
2020-10-03 08:55:51 upgrade gir1.2-pango-1.0:amd64 1.46.1-1 1.46.2-1
2020-10-03 08:55:51 upgrade libpangoxft-1.0-0:amd64 1.46.1-1 1.46.2-1
2020-10-03 08:55:51 upgrade libpangoft2-1.0-0:amd64 1.46.1-1 1.46.2-1
2020-10-03 08:55:51 upgrade libpango-1.0-0:amd64 1.46.1-1 1.46.2-1
2020-10-03 08:55:52 upgrade libpangocairo-1.0-0:amd64 1.46.1-1 1.46.2-1
2020-10-03 08:55:52 upgrade libgjs0g:amd64 1.64.3-1 1.66.0-1
2020-10-03 08:55:52 upgrade gir1.2-gdm-1.0:amd64 3.36.3-1 3.38.0-2
2020-10-03 08:55:52 upgrade mutter-common:all 3.36.6-1 3.38.0-2
2020-10-03 08:55:53 upgrade mutter:amd64 3.36.6-1 3.38.0-2
2020-10-03 08:55:53 upgrade libgdata-common:all 0.17.12-1 0.17.13-1
2020-10-03 08:55:53 upgrade libgdata22:amd64 0.17.12-1 0.17.13-1
2020-10-03 08:55:53 upgrade gir1.2-gdata-0.0:amd64 0.17.12-1 0.17.13-1
2020-10-03 08:55:53 upgrade gnome-control-center:amd64 1:3.36.4-1 1:3.38.0-2
2020-10-03 08:55:53 upgrade gnome-control-center-data:all 1:3.36.4-1 1:3.38.0-2
2020-10-03 13:17:06 upgrade four-in-a-row:amd64 1:3.36.2-1 1:3.38.0-1
2020-10-03 13:17:06 upgrade libgoa-1.0-common:all 3.36.0-1 3.37.90-2
2020-10-03 13:17:06 upgrade gnome-online-accounts:amd64 3.36.0-1 3.37.90-2
2020-10-03 13:17:07 upgrade libgoa-backend-1.0-1:amd64 3.36.0-1 3.37.90-2
2020-10-03 13:17:07 upgrade libgoa-1.0-0b:amd64 3.36.0-1 3.37.90-2
2020-10-03 13:17:07 upgrade gir1.2-goa-1.0:amd64 3.36.0-1 3.37.90-2
2020-10-03 13:17:07 upgrade gnome-contacts:amd64 3.36.2-1 3.38-1
2020-10-03 13:17:07 upgrade gvfs-backends:amd64 1.44.1-1+b1 1.46.0-2
2020-10-03 13:17:07 upgrade gvfs:amd64 1.44.1-1+b1 1.46.0-2
2020-10-03 13:17:07 upgrade gvfs-daemons:amd64 1.44.1-1+b1 1.46.0-2
2020-10-03 13:17:08 upgrade gvfs-libs:amd64 1.44.1-1+b1 1.46.0-2
2020-10-03 13:17:08 upgrade gvfs-common:all 1.44.1-1 1.46.0-2
2020-10-04 20:26:11 upgrade fonts-noto-color-emoji:all 0~20200408-1 0~20200916-1
2020-10-04 20:26:12 upgrade librsvg2-common:amd64 2.48.8+dfsg-1 2.50.0+dfsg-1
2020-10-04 20:26:12 upgrade librsvg2-2:amd64 2.48.8+dfsg-1 2.50.0+dfsg-1
2020-10-04 20:26:12 upgrade gir1.2-rsvg-2.0:amd64 2.48.8+dfsg-1 2.50.0+dfsg-1

**Comment by maoschanz** [comment] 2020-10-05 02:24
duplicate of #133, read what's in that issue

**Closed by maoschanz** 2020-10-05 02:24 UTC
